#11 create class for parsing command
JujaLabs/keepers-slack-bot pull request #19
Opened 2017-07-16 19:29 UTC by ksergey12

connect to #11

2017-07-16 20:37 UTC, NikolayNN requested changes

2017-07-16 20:37 UTC, NikolayNN commented on src/main/java/ua/com/juja/microservices/keepers/slackbot/model/SlackParsedCommand.java
> +            throw new WrongCommandFormatException(String.format("The text '%s' doesn't contains slackName", text));
contain without 's'

2017-07-16 20:37 UTC, NikolayNN commented on src/test/java/ua/com/juja/microservices/keepers/slackbot/model/SlackParsedCommandTest.java
> +                result.toString());
The text "text @slack2 text@slack1 text @slack3" has three slackNames, but result has only two Users

2017-07-16 20:37 UTC, NikolayNN commented on src/main/java/ua/com/juja/microservices/keepers/slackbot/model/SlackParsedCommand.java
> +    private String from;
rename the field to fromSlackName

2017-07-16 20:37 UTC, NikolayNN commented on src/main/java/ua/com/juja/microservices/keepers/slackbot/model/SlackParsedCommand.java
> +        userCount = slackNames.size();
add logger.debug here with text "SlackParsedCommand created. fromSlackName: {} text: {} slackNames in the text {slackNames.toString} users: {users.toString}"
or you can do better

2017-07-16 20:37 UTC, NikolayNN commented on src/main/java/ua/com/juja/microservices/keepers/slackbot/model/SlackParsedCommand.java
>          this.from = from;
rename to fromSlackName

2017-07-16 20:37 UTC, NikolayNN commented on src/main/java/ua/com/juja/microservices/keepers/slackbot/model/SlackParsedCommand.java
> +        return new LinkedList(usersCopy.values());
We have recently decided to output more information in a debug log. And I think that we should output users from the LinkedList to debug log instead userCount.

2017-07-16 20:41 UTC, NikolayNN requested changes

2017-07-16 20:41 UTC, NikolayNN commented on src/main/java/ua/com/juja/microservices/keepers/slackbot/model/SlackParsedCommand.java
> +    private List<String> slackNames;
I think better name to the field slackNamesInText

2017-07-17 19:23 UTC, ksergey12 commented on src/test/java/ua/com/juja/microservices/keepers/slackbot/model/SlackParsedCommandTest.java
> +                result.toString());
Fixed.

2017-07-17 19:23 UTC, ksergey12 commented on src/main/java/ua/com/juja/microservices/keepers/slackbot/model/SlackParsedCommand.java
> +    private String from;
Done.

2017-07-17 19:23 UTC, ksergey12 commented on src/main/java/ua/com/juja/microservices/keepers/slackbot/model/SlackParsedCommand.java
>          this.from = from;
Done.

2017-07-17 19:23 UTC, ksergey12 commented on src/main/java/ua/com/juja/microservices/keepers/slackbot/model/SlackParsedCommand.java
> +        userCount = slackNames.size();
Done.

2017-07-17 19:24 UTC, ksergey12 commented on src/main/java/ua/com/juja/microservices/keepers/slackbot/model/SlackParsedCommand.java
> +        return new LinkedList(usersCopy.values());
Done.

2017-07-17 19:24 UTC, ksergey12 commented on src/main/java/ua/com/juja/microservices/keepers/slackbot/model/SlackParsedCommand.java
> +            throw new WrongCommandFormatException(String.format("The text '%s' doesn't contains slackName", text));
Fixed.

2017-07-17 19:24 UTC, ksergey12 commented on src/main/java/ua/com/juja/microservices/keepers/slackbot/model/SlackParsedCommand.java
> +    private List<String> slackNames;
Fixed.

2017-07-17 20:10 UTC, NikolayNN requested changes

2017-07-17 20:10 UTC, NikolayNN commented on src/main/java/ua/com/juja/microservices/keepers/slackbot/model/SlackParsedCommand.java
> +    public List<UserDTO> receiveAllUsers() {
rename to getAllUsers

2017-07-17 20:10 UTC, NikolayNN commented on src/main/java/ua/com/juja/microservices/keepers/slackbot/model/SlackParsedCommand.java
> +    public UserDTO receiveFirstUser() {
rename to getFirstUser

2017-07-17 20:10 UTC, NikolayNN commented on src/main/java/ua/com/juja/microservices/keepers/slackbot/model/SlackParsedCommand.java
> +    public UserDTO receiveFromUser() {
rename to getFromUser

2017-07-18 06:45 UTC, ksergey12 commented on src/main/java/ua/com/juja/microservices/keepers/slackbot/model/SlackParsedCommand.java
> +    public List<UserDTO> receiveAllUsers() {
Done.

2017-07-18 06:46 UTC, ksergey12 commented on src/main/java/ua/com/juja/microservices/keepers/slackbot/model/SlackParsedCommand.java
> +    public UserDTO receiveFirstUser() {
Done.

2017-07-18 06:46 UTC, ksergey12 commented on src/main/java/ua/com/juja/microservices/keepers/slackbot/model/SlackParsedCommand.java
> +    public UserDTO receiveFromUser() {
Done.

2017-07-18 08:04 UTC, NikolayNN approved these changes

2017-07-18 20:44 UTC, OlgaKulikova approved these changes

2017-07-18 20:44 UTC, merged