#17 implement feature slb f3
JujaLabs/keepers-slack-bot pull request #30
Opened 2017-07-31 17:52 UTC by ksergey12

connect to #17

2017-07-31 21:15 UTC, asidun commented
Your change request so dirty. It includes not only your changes. Please, be careful during the next requests!

2017-07-31 21:27 UTC, asidun requested changes

2017-07-31 21:27 UTC, asidun commented on src/main/java/ua/com/juja/microservices/keepers/slackbot/controller/KeepersSlackCommandController.java
> +            response = "За Хранителем " + keeperSlackName + " сейчас не закреплено ни одно направление.";
I propose to write responses on English. Do you have some other agreement with the team?

2017-07-31 21:27 UTC, asidun commented on src/main/java/ua/com/juja/microservices/keepers/slackbot/dao/impl/RestKeeperRepository.java
> +        List<String> result;
You should initialize result by empty List. Otherwise, in some situations, you can get Null Pointer Ex

2017-07-31 21:31 UTC, asidun commented on src/main/java/ua/com/juja/microservices/keepers/slackbot/dao/impl/RestKeeperRepository.java
> +        HttpEntity<String> request = new HttpEntity<>(setupBaseHttpHeaders());
Why do you delete uuid?

2017-07-31 21:34 UTC, asidun commented on src/test/java/ua/com/juja/microservices/keepers/slackbot/service/impl/DefaultKeeperServiceTest.java
> +                .thenReturn(new ArrayList<>(Arrays.asList("direction1", "direction2")));
You should use expectedList  instead new ArrayList

2017-07-31 21:38 UTC, asidun requested changes

2017-07-31 21:38 UTC, asidun commented on src/test/java/ua/com/juja/microservices/keepers/slackbot/dao/impl/RestKeeperRepositoryTest.java
> +        mockServer.verify();
Why do you execute verify() method?

2017-07-31 21:38 UTC, asidun commented on src/test/java/ua/com/juja/microservices/keepers/slackbot/dao/impl/RestKeeperRepositoryTest.java
> +        assertEquals(actualList.size(), 2);
You check that you have got only two elements in the next row.

2017-07-31 21:40 UTC, asidun commented on src/test/java/ua/com/juja/microservices/keepers/slackbot/controller/KeepersSlackCommandControllerTest.java
> +    public void onReceiveSlashCommandGetKeeperDirectionsReturnEmptyRichMessage() throws Exception {
Dou you know about unit test naming convention. Ivan wrote in slack chat 2-3 weeks ago.

2017-07-31 21:44 UTC, asidun commented
I did not see acceptance and integration tests.

2017-08-01 06:51 UTC, OlgaKulikova commented on src/main/java/ua/com/juja/microservices/keepers/slackbot/controller/KeepersSlackCommandController.java
> +            response = "За Хранителем " + keeperSlackName + " сейчас не закреплено ни одно направление.";
only English, right!

2017-08-01 06:59 UTC, OlgaKulikova commented
@ksergey12 You made pull request to master branch instead of develop. Please do all necessary changes and then change target branch to develop.

2017-08-01 08:00 UTC, ksergey12 commented on src/main/java/ua/com/juja/microservices/keepers/slackbot/controller/KeepersSlackCommandController.java
> +            response = "За Хранителем " + keeperSlackName + " сейчас не закреплено ни одно направление.";
In specification those lines stated in Russian (SLB-F3-RSP). If so, I change them.

2017-08-01 08:22 UTC, ksergey12 commented on src/test/java/ua/com/juja/microservices/keepers/slackbot/dao/impl/RestKeeperRepositoryTest.java
> +        mockServer.verify();
I'm using it to to ensure that all expected requests were actually performed. Moreover, it is used in tests for Gamification slack bot. Do you think it's not necessary here?

2017-08-01 08:34 UTC, ksergey12 commented on src/test/java/ua/com/juja/microservices/keepers/slackbot/controller/KeepersSlackCommandControllerTest.java
> +    public void onReceiveSlashCommandGetKeeperDirectionsReturnEmptyRichMessage() throws Exception {
No, I don't.
@OlgaKulikova Do we have a wiki page with mentioned conventions?
It's widely used name pattern in Gamification slack bot tests and I used it respectively.
If possible please propose your version.

2017-08-01 08:54 UTC, ksergey12 commented on src/main/java/ua/com/juja/microservices/keepers/slackbot/dao/impl/RestKeeperRepository.java
> +        List<String> result;
Done.

2017-08-01 08:55 UTC, ksergey12 commented on src/main/java/ua/com/juja/microservices/keepers/slackbot/dao/impl/RestKeeperRepository.java
> +        HttpEntity<String> request = new HttpEntity<>(setupBaseHttpHeaders());
I asked Nikolay about it and we decided that it is not necessary.

2017-08-01 08:56 UTC, ksergey12 commented on src/test/java/ua/com/juja/microservices/keepers/slackbot/service/impl/DefaultKeeperServiceTest.java
> +                .thenReturn(new ArrayList<>(Arrays.asList("direction1", "direction2")));
Done.

2017-08-01 09:01 UTC, ksergey12 commented on src/test/java/ua/com/juja/microservices/keepers/slackbot/dao/impl/RestKeeperRepositoryTest.java
> +        assertEquals(actualList.size(), 2);
Sorry, I don't understand what shall I check? Could you please explain?

2017-08-01 20:02 UTC, OlgaKulikova commented on src/test/java/ua/com/juja/microservices/keepers/slackbot/controller/KeepersSlackCommandControllerTest.java
> +    public void onReceiveSlashCommandGetKeeperDirectionsReturnEmptyRichMessage() throws Exception {
@ksergey12 There is no wiki page yet but you can read this article first. 
@asidun I think we won't have a strict name convention for unit tests. The most idea - the name of test must reveal the contents - what we want to test,  and if we can have several results then the expected result can be mentioned in the name of the test.

2017-08-03 12:32 UTC, asidun commented on src/test/java/ua/com/juja/microservices/keepers/slackbot/dao/impl/RestKeeperRepositoryTest.java
> +        mockServer.verify();
No. All is ok. I mean that you should know what do you copy-paste )))

2017-08-03 13:48 UTC, asidun commented on src/test/java/ua/com/juja/microservices/keepers/slackbot/dao/impl/RestKeeperRepositoryTest.java
> +        assertEquals(actualList.size(), 2);
I mean that not need check  assertEquals(actualList.size(), 2), because on the next row you check that in array have only two certain elements.

2017-08-04 14:26 UTC, OlgaKulikova requested changes

2017-08-04 14:26 UTC, OlgaKulikova commented on src/main/java/ua/com/juja/microservices/keepers/slackbot/controller/KeepersSlackCommandController.java
> +            response = "A keeper " + keeperSlackName + " have no active directions.";
`"The keeper "`...`"has`

2017-08-04 14:26 UTC, OlgaKulikova commented on src/main/java/ua/com/juja/microservices/keepers/slackbot/controller/KeepersSlackCommandController.java
> +            response = "A keeper " + keeperSlackName + " active directions are: " + result.toString();
`"The keeper " + keeperSlackName + " has active directions: " + result.toString();`

2017-08-04 14:26 UTC, OlgaKulikova commented on src/test/java/ua/com/juja/microservices/integration/KeeperSlackBotIntegrationTest.java
> +        mockSuccessKeepersService(urlBaseKeeper + "/f2034f22-562b-4e02-bfcf-ec615c1ba62b",
it's better to pass to private method the expected HTTP method as well.

2017-08-04 14:26 UTC, OlgaKulikova commented on src/test/java/ua/com/juja/microservices/keepers/slackbot/controller/KeepersSlackCommandControllerTest.java
> +                        .value("A keeper @slack1 have no active directions."));
`"The keeper @slack1 has..."`

2017-08-04 14:26 UTC, OlgaKulikova commented on src/test/java/ua/com/juja/microservices/keepers/slackbot/controller/KeepersSlackCommandControllerTest.java
> +                        .value("A keeper @slack1 active directions are: [direction1, direction2]"));
`"The keeper @slack1 has active directions: ..."`

2017-08-04 15:15 UTC, ksergey12 commented on src/main/java/ua/com/juja/microservices/keepers/slackbot/controller/KeepersSlackCommandController.java
> +            response = "A keeper " + keeperSlackName + " have no active directions.";
Fixed.

2017-08-04 15:16 UTC, ksergey12 commented on src/main/java/ua/com/juja/microservices/keepers/slackbot/controller/KeepersSlackCommandController.java
> +            response = "A keeper " + keeperSlackName + " active directions are: " + result.toString();
Fixed.

2017-08-04 15:17 UTC, ksergey12 commented on src/test/java/ua/com/juja/microservices/integration/KeeperSlackBotIntegrationTest.java
> +        mockSuccessKeepersService(urlBaseKeeper + "/f2034f22-562b-4e02-bfcf-ec615c1ba62b",
I changed that method respectively.

2017-08-04 15:17 UTC, ksergey12 commented on src/test/java/ua/com/juja/microservices/keepers/slackbot/controller/KeepersSlackCommandControllerTest.java
> +                        .value("A keeper @slack1 have no active directions."));
Fixed.

2017-08-04 15:17 UTC, ksergey12 commented on src/test/java/ua/com/juja/microservices/keepers/slackbot/controller/KeepersSlackCommandControllerTest.java
> +                        .value("A keeper @slack1 active directions are: [direction1, direction2]"));
Fixed.

2017-08-09 07:50 UTC, OlgaKulikova approved these changes

2017-08-10 12:30 UTC, asidun approved these changes

2017-08-10 12:44 UTC, merged