Moved slackNameHandlerService from KeeperSlackCommandController to DefaultKeeperService
JujaLabs/keepers-slack-bot pull request #36
Opened 2017-08-13 12:47 UTC by Solykk

Connect #35 
changed KeeperServiceInterface
changed KeeperRepositoryInterface
added @EqualsAndHashCode to KeeperRequest
corrected tests after refactoring

2017-08-13 19:10 UTC, NikolayNN approved these changes
and please to do code format in the classes. You can do it automatically, use this hot key CTRL+ALT+L

2017-08-13 19:10 UTC, NikolayNN commented on src/main/java/ua/com/juja/microservices/keepers/slackbot/service/impl/DefaultKeeperService.java
> +        return result;
I think better:
if (ids.length > 0) {
            return String.format("Keeper: %s in direction: %s dismissed" ,
                    slackParsedCommand.getFirstUserFromText().getSlack(), keeperRequest.getDirection());
}else{
            return "ERROR. Something went wrong. Keeper was not dismissed :(";
}
and below

2017-08-13 19:10 UTC, NikolayNN commented on src/test/java/ua/com/juja/microservices/keepers/slackbot/controller/KeepersSlackCommandControllerTest.java
>          final String KEEPER_ADD_COMMAND_TEXT = "@slack_name teems";
correct - teams

2017-08-13 19:10 UTC, NikolayNN commented on src/test/java/ua/com/juja/microservices/keepers/slackbot/controller/KeepersSlackCommandControllerTest.java
> +        when(keeperService.getKeeperDirections(any(String.class), any(String.class)))
it is so abstact test. you should check the Strings.

2017-08-13 19:11 UTC, NikolayNN requested changes
and please to do code format in the classes. You can do it automatically, use this hot key CTRL+ALT+L

2017-08-14 18:11 UTC, Solykk commented on src/main/java/ua/com/juja/microservices/keepers/slackbot/service/impl/DefaultKeeperService.java
> +        return result;
fixed

2017-08-14 18:12 UTC, Solykk commented on src/test/java/ua/com/juja/microservices/keepers/slackbot/controller/KeepersSlackCommandControllerTest.java
>          final String KEEPER_ADD_COMMAND_TEXT = "@slack_name teems";
fixed

2017-08-14 18:12 UTC, Solykk commented on src/test/java/ua/com/juja/microservices/keepers/slackbot/controller/KeepersSlackCommandControllerTest.java
> +        when(keeperService.getKeeperDirections(any(String.class), any(String.class)))
fixed

2017-08-15 07:30 UTC, NikolayNN approved these changes

2017-08-15 07:36 UTC, merged