#27 refactoring slack parsed command and slack name handler service
JujaLabs/keepers-slack-bot pull request #37
Opened 2017-08-16 19:32 UTC by ksergey12

connect to #27

2017-08-17 17:30 UTC, NikolayNN requested changes

2017-08-17 17:30 UTC, NikolayNN commented on src/test/java/ua/com/juja/microservices/keepers/slackbot/model/SlackParsedCommandTest.java
> +        usersInText.add(new UserDTO("uuid3", "@slack3"));
I think the list for each test should be contains specific users accordance with the text.
for example 
"text text @slack1 text" 
usersInText must contains only one object UserDTO

2017-08-17 17:30 UTC, NikolayNN commented on src/test/java/ua/com/juja/microservices/keepers/slackbot/model/SlackParsedCommandTest.java
> +        String text = "text @slack text";
the text contains only one slackName, but in the test
assertEquals(3, slackParsedCommand.getUserCountInText());

2017-08-17 18:01 UTC, ksergey12 commented on src/test/java/ua/com/juja/microservices/keepers/slackbot/model/SlackParsedCommandTest.java
> +        usersInText.add(new UserDTO("uuid3", "@slack3"));
Fixed.

2017-08-17 18:02 UTC, ksergey12 commented on src/test/java/ua/com/juja/microservices/keepers/slackbot/model/SlackParsedCommandTest.java
> +        String text = "text @slack text";
Fixed.

2017-08-18 09:45 UTC, NikolayNN requested changes

2017-08-18 09:45 UTC, NikolayNN commented on src/main/java/ua/com/juja/microservices/keepers/slackbot/model/SlackParsedCommand.java
> +        userCountInText = usersInText.size();
delete the field userCountInText

2017-08-18 09:45 UTC, NikolayNN commented on src/main/java/ua/com/juja/microservices/keepers/slackbot/model/SlackParsedCommand.java
> +        return userCountInText;
return usersInText.size();

2017-08-18 10:06 UTC, ksergey12 commented on src/main/java/ua/com/juja/microservices/keepers/slackbot/model/SlackParsedCommand.java
> +        userCountInText = usersInText.size();
Done.

2017-08-18 10:06 UTC, ksergey12 commented on src/main/java/ua/com/juja/microservices/keepers/slackbot/model/SlackParsedCommand.java
> +        return userCountInText;
Done.

2017-08-18 16:40 UTC, NikolayNN requested changes

2017-08-18 16:40 UTC, NikolayNN commented on src/main/java/ua/com/juja/microservices/keepers/slackbot/model/SlackParsedCommand.java
> +        return result;
You can just use  anotation  @EqualsAndHashCode of lombok.
And add the Annotation to UserDTO

2017-08-18 16:40 UTC, NikolayNN commented on src/test/java/ua/com/juja/microservices/keepers/slackbot/service/impl/SlackNameHandlerServiceTest.java
> +        assertTrue(expected.hashCode() == actual.hashCode());
it is redaundant check, if object equals then hashCode equals

2017-08-19 08:36 UTC, ksergey12 commented on src/main/java/ua/com/juja/microservices/keepers/slackbot/model/SlackParsedCommand.java
> +        return result;
Done.

2017-08-19 08:36 UTC, ksergey12 commented on src/test/java/ua/com/juja/microservices/keepers/slackbot/service/impl/SlackNameHandlerServiceTest.java
> +        assertTrue(expected.hashCode() == actual.hashCode());
Fixed.

2017-08-19 13:21 UTC, NikolayNN approved these changes

2017-08-19 20:51 UTC, OlgaKulikova approved these changes

2017-08-19 20:51 UTC, merged